# Generated by Django 3.2.8 on 2021-10-22 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advisor2', '0003_auto_20211023_0003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advisor',
            old_name='booking_id',
            new_name='booking',
        ),
        migrations.RenameField(
            model_name='advisor',
            old_name='user_id',
            new_name='user',
        ),
    ]
