# Generated by Django 3.2.8 on 2021-10-22 18:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('advisor2', '0004_auto_20211023_0013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advisor',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='advisor',
            name='user',
        ),
        migrations.AddField(
            model_name='booking',
            name='advisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='advisor2.advisor'),
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
