# Generated by Django 3.2.8 on 2021-10-23 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advisor2', '0005_auto_20211023_0022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='advisor',
            new_name='adid',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='user',
            new_name='uid',
        ),
    ]
